version: '3'

services:
  database:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - 5432:5432
  app:
    build: .
    container_name: docker-scraper
    ports:
    - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
    depends_on:
      - database
    restart: on-failure
